### ISSUE TITLE
Windows download sets off anti-virus warning for Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by jonthysell** [edre/nokamute#1]
Hi, just tried to download the windows build of 0.2.0 but it was blocked by Windows Defender.

![image](https://user-images.githubusercontent.com/10852185/173130535-101dac15-39ce-431c-9fd6-d93e8f84feb3.png)

**Comment by edre** [comment]
Interesting. I ran it through VirusTotal and dozens of other antivirus software didn't find any issues: https://www.virustotal.com/gui/url/5171808abe4336f31ba219ac3fd34de564eee32015f19323a1941819ef572412

**Comment by edre** [comment]
Does any previous release get blocked as well?

**Comment by jonthysell** [comment]
Yeah, all of a sudden they're getting flagged too.

It looks like it's hitting rust project in general? https://github.com/rust-lang/rust/issues/88297

**Comment by jonthysell** [comment]
Ok, I got Windows Defender to update and now it's not getting flagged anymore.

![image](https://user-images.githubusercontent.com/10852185/173161982-61500a8c-5b77-440e-aa96-6040c746850f.png)
