### ISSUE TITLE
Illegal ladybug move

### ISSUE THREAD

**Issue by Positivapatrik** [edre/nokamute#4]
I don't know if this is helpful or not, but nokamute tried to play an illegal move against me which mzingaviewer refused, but here is the start/end of the gamelog (which is too long to post in its entirety) and pgn anyway.
Also, amazing work with nokamute. It is definitely very strong! ⭐ 

```
id nokamute 0.2.3
Mosquito;Ladybug;Pillbug
ok
options
Aggression;int;3;3;1;5
BackgroundPondering;bool;False;False
NumThreads;int;4;4;1;4
RandomOpening;bool;False;False
TableSizeMiB;int;100;100;1;256
Verbose;bool;False;False
ok
options set Aggression 1
Aggression;int;1;3;1;5
ok
options set BackgroundPondering True
BackgroundPondering;bool;True;False
ok
newgame Base+MLP
Base+MLP;NotStarted;White[1]
ok
validmoves
wG1;wS1;wA1;wB1;wM;wL;wP
ok
bestmove time 00:00:30
wG1
ok
play wG1

...

play bB1 wB1
Base+MLP;InProgress;White[15];wG1;bP wG1-;wA1 \wG1;bB1 bP\;wQ -wA1;bQ bB1-;wP wQ\;bA1 \bQ;wA1 bA1/;bG1 bB1\;wM \wA1;bS1 /bG1;wA2 \wG1;bA2 /bB1;wA3 wP\;bA2 \wM;wA3 \bA2;bB1 bP;wS1 wA1/;bS1 bQ-;wA2 -bG1;bB1 wG1;wB1 /wQ;bM \bP;wL -wA3;bM bB1\;wB1 \bB1;bB1 wB1
ok
validmoves
wL bA2/;wL wL\;wL \wS1;wL /bA2;wS1 wA3/;wS1 bS1/;wQ \bB1;wQ /wQ;wQ /wP;wQ wP\;wP /wQ;wP wP\;wA2 \wL;wA2 \wA3;wA2 wA3/;wA2 -wL;wA2 bA2/;wA2 /wL;wA2 wL\;wA2 \wS1;wA2 wS1/;wA2 \wQ;wA2 \bB1;wA2 bB1/;wA2 /bA2;wA2 wS1-;wA2 -wQ;wA2 \bP;wA2 /wM;wA2 wS1\;wA2 /wQ;wA2 wA1\;wA2 bS1/;wA2 /wP;wA2 wP\;wA2 bS1-;wA2 /bM;wA2 bQ\;wA2 bS1\;wA2 wA2\;wA2 bG1\;wG2 /wA2;wS2 /wA2;wB2 /wA2;wG2 /wP;wS2 /wP;wB2 /wP;wG2 /wQ;wS2 /wQ;wB2 /wQ;wG2 \wQ;wS2 \wQ;wB2 \wQ;wG2 -wQ;wS2 -wQ;wB2 -wQ;wG2 wS1\;wS2 wS1\;wB2 wS1\;wG2 wS1/;wS2 wS1/;wB2 wS1/;wG2 wS1-;wS2 wS1-;wB2 wS1-;wG2 \wA3;wS2 \wA3;wB2 \wA3;wG2 wA3/;wS2 wA3/;wB2 wA3/;wG2 \wL;wS2 \wL;wB2 \wL;wG2 /wL;wS2 /wL;wB2 /wL;wG2 -wL;wS2 -wL;wB2 -wL
ok
bestmove time 00:00:30
wL wL\
ok
play wL wG1\
invalidmove That is not a valid move
ok
```

And game pgn up to the illegal move wL wG1\\

> [GameType "Base+MLP"]
> [Date "2022.12.15"]
> [Event ""]
> [Site ""]
> [Round ""]
> [White "nokamute 0.2.3"]
> [Black "paber"]
> [Result "InProgress"]
> 
> 1. wG1
> 2. bP wG1-
> 3. wA1 \wG1
> 4. bB1 bP\
> 5. wQ -wA1
> 6. bQ bB1-
> 7. wP wQ\
> 8. bA1 \bQ
> 9. wA1 bA1/
> 10. bG1 bB1\
> 11. wM \wA1
> 12. bS1 /bG1
> 13. wA2 \wG1
> 14. bA2 /bB1
> 15. wA3 wP\
> 16. bA2 \wM
> 17. wA3 \bA2
> 18. bB1 bP
> 19. wS1 wA1/
> 20. bS1 bQ-
> 21. wA2 -bG1
> 22. bB1 wG1
> 23. wB1 /wQ
> 24. bM \bP
> 25. wL -wA3
> 26. bM bB1\
> 27. wB1 \bB1
> 28. bB1 wB1

**Comment by Positivapatrik** [comment]
Looked a bit more and I guess this issue is not an issue with nokamute, but with mzingaviewer. It looks like the attempted move was wL wL\\ which is legal, but somehow I guess mzingaviewer translated that to wL wG1\\. If I understand how the engine-viewer communication works. When I reloaded the pgn and played from there it did make wL wL\\ correctly so I guess nothing more to say here ^^. 

And again thanks for contributing by making a hive bot :D.

**Comment by edre** [comment]
Thanks for filing a bug! I agree that this doesn't look reproducible from the nokamute side. Maybe going through this game log can reproduce on MzingaViewer?
